const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
function load(){const ctx={window:{}};vm.createContext(ctx);for(const f of ['sources','catalog','routes','applicability'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/'+f+'.js'),'utf8'),ctx);return ctx.window;}
test('608条原文建议都有有效、独立的适用前提',()=>{const w=load(),a=w.LifeApplicability,known=new Set(a.contexts.map(c=>c.id));assert.equal(w.LifeCatalog.all.length,608);for(const c of w.LifeCatalog.all){const r=a.get(c);assert.ok(r&&r.reason);assert.equal(r.mode,r.requires.length?'conditional':'general');for(const id of r.requires)assert.ok(known.has(id),c.id+': '+id);assert.equal(a.eligible(c,r.requires),true);for(const id of r.requires)assert.equal(a.eligible(c,r.requires.filter(x=>x!==id)),false);}assert.equal(a.get('missing'),null);assert.equal(a.eligible('missing',Array.from(known)),false);});
test('求职事实不解锁在职、劳动纠纷、工伤和网站经营建议',()=>{const {LifeApplicability:a,LifeCatalog:c}=load();assert.equal(a.eligible('source-7-5',['job_search']),true);for(const card of c.all){const r=a.get(card);if(r.requires.some(id=>['employed','labor_dispute','work_injury','site_operator','business'].includes(id)))assert.equal(a.eligible(card,['job_search']),false,card.id);}assert.equal(a.eligible('source-7-1',['job_search']),false);assert.equal(a.eligible('source-7-1',['unemployed']),true);});
test('职业兴趣或在职不足以解锁工伤与平台责任',()=>{const a=load().LifeApplicability;for(const id of ['source-19-12','source-19-14','source-19-15']){assert.equal(a.eligible(id,['employed','labor_dispute']),false);assert.equal(a.eligible(id,['work_injury']),true);}for(const id of ['source-11-16','source-11-17','source-26-1','source-26-4','source-26-11']){assert.equal(a.eligible(id,['job_search','employed','technical_work','business']),false);assert.equal(a.eligible(id,['site_operator']),true);}});
test('儿童和慢性病前提不会从方向、年龄阶段或点击继承',()=>{const w=load(),a=w.LifeApplicability;for(const c of w.LifeCatalog.all.filter(c=>c.chapterId===30))assert.equal(a.eligible(c,['family','job_search']),false);assert.equal(a.eligible('source-16-7',['chronic_care']),false);assert.equal(a.eligible('source-16-7',['chronic_care','specific_health','health_source_16_7']),true);assert.equal(a.eligible('source-30-4',['student_care']),true);});
test('所有八方面有可探索的通用条目，原始冷启动保留',()=>{const w=load(),a=w.LifeApplicability;for(const aspect of w.LifeRoutes.aspects)assert.ok(w.LifeRoutes.cards(aspect.id).some(c=>a.eligible(c,[])),aspect.id);for(const id of ['source-3-1','source-14-2','source-5-23','source-4-1','source-14-6','source-5-24'])assert.equal(a.get(id).mode,'general');});
test('读取元数据不能改写前提或建议原文',()=>{const w=load(),c=w.LifeCatalog.all.map(c=>[c.id,c.title,c.text]);const copy=w.LifeApplicability.get('source-11-16');copy.requires.length=0;assert.equal(w.LifeApplicability.eligible('source-11-16',[]),false);assert.deepEqual(w.LifeCatalog.all.map(c=>[c.id,c.title,c.text]),c);});

test('特定医疗条件逐条隔离，确认一种症状不放行另一种',()=>{const w=load(),a=w.LifeApplicability,all=a.contexts.map(c=>c.id);const healthCards=w.LifeCatalog.all.filter(c=>a.get(c).requires.includes('specific_health'));assert.ok(healthCards.length>0);const seen=new Set();for(const card of healthCards){const flag='health_'+card.id.replace(/-/g,'_'),r=a.get(card);assert.ok(r.requires.includes(flag));assert.ok(!seen.has(flag));seen.add(flag);const context=a.contexts.find(c=>c.id===flag);assert.ok(context.title.includes(card.title));assert.equal(a.eligible(card,all.filter(id=>id!==flag)),false);assert.equal(a.eligible(card,r.requires),true);}const diabetes=a.get('source-16-7').requires;assert.equal(a.eligible('source-16-7',diabetes),true);assert.equal(a.eligible('source-16-8',diabetes),false);assert.equal(a.eligible('source-16-9',diabetes),false);assert.equal(a.eligible('source-1-8',['specific_health']),false);});

test('通用慢病管理不能放行高血压用药或糖尿病急救',()=>{const a=load().LifeApplicability,base=a.get('source-16-1').requires,ids=['source-1-7','source-1-29','source-2-12','source-13-17'];assert.equal(a.eligible('source-16-1',base),true);for(const id of ids){assert.equal(a.eligible(id,base),false);const confirmed=a.get(id).requires;assert.equal(a.eligible(id,confirmed),true);for(const other of ids.filter(x=>x!==id))assert.equal(a.eligible(other,confirmed),false);}});
