const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
function env(storage){const c={console,Date,Set,Number,setTimeout,clearTimeout,localStorage:storage||{getItem:()=>null,setItem(){}}};c.window=c;vm.createContext(c);['content','core','platform'].forEach(f=>vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets',f+'.js'),'utf8'),c));return c;}
test('人生阶段开局，81条四问路径，三选一并保留33章覆盖',()=>{const c=env(),C=c.LifeCore,chapters=new Set(),ids=new Set();let paths=0;for(const st of c.LifeContent.stages)for(const g of c.LifeContent.goals)for(const d of g.domains)for(const s of c.LifeContent.domains[d].scenes){s.cards.forEach(a=>ids.add(a.id));s.chapters.forEach(id=>chapters.add(id));let a=[];for(const id of [st.id,g.id,d,s.id]){assert.equal(C.question(a).options.length,3);a=C.answer(a,id);}assert.equal(C.question(a),null);const cards=C.recommend(a);assert.equal(cards.length,3);assert(cards.every(x=>x.sceneId===s.id&&x.stageId===st.id&&x.steps.length===3));assert(C.validate(Object.assign(C.initial(),{answers:a})));paths++;}assert.equal(paths,81);assert.equal(ids.size,81);assert.equal(chapters.size,33);});
test('不存在的选项与跨目标注入被拒绝',()=>{const C=env().LifeCore;assert.throws(()=>C.answer([],'money'));assert.throws(()=>C.answer(['starting','choose'],'money'));assert.throws(()=>C.recommend(['starting','better','career','firstpath']));assert.equal(C.validate({version:1,answers:['choose','money'],deck:[],visited:[]}),false);});
test('收藏防重，回退不改变已收藏快照，完成状态可持久化',()=>{const C=env().LifeCore;let s=C.initial();s.answers=['building','better','money','subscription'];const c=C.recommend(s.answers)[0];s=C.collect(s,c,null);assert.equal(s.deck.length,1);assert.equal(C.collect(s,c,null).deck.length,1);c.steps[0]='later mutated';assert.notEqual(s.deck[0].steps[0],'later mutated');s.answers=[];s.deck[0].done=true;assert(C.validate(s));});
test('收益计算验证、费用净额与时间口径',()=>{const C=env().LifeCore;assert.equal(C.calc('subscription',{fee:30,months:12}).value,360);assert.equal(C.calc('plan',{old:80,next:100,cost:50,months:12}).value,-290);assert.equal(C.calc('commute',{minutes:15,days:20}).value,5);for(const vals of [{fee:'',months:12},{fee:-1,months:12},{fee:10,months:0},{fee:10,months:1.2},{fee:Infinity,months:12}])assert.throws(()=>C.calc('subscription',vals));assert.throws(()=>C.calc('commute',{minutes:30,days:32}));});
test('损坏记录不覆盖，读写失败有明确错误',()=>{let writes=0;const c=env({getItem:()=>'{bad',setItem:()=>writes++});assert(c.LifePlatform.load().error);assert.throws(()=>c.LifePlatform.save(c.LifeCore.initial()));assert.equal(writes,0);const d=env({getItem:()=>null,setItem(){throw Error('quota');}});assert.equal(d.LifePlatform.load().data,null);assert.throws(()=>d.LifePlatform.save(d.LifeCore.initial()),/保存失败/);});
test('相册桥只在主动调用后执行，失败不声称保存',async()=>{const c=env();assert.equal((await c.LifePlatform.saveImage('data:image/png;base64,abc')).saved,false);let calls=0;c.xhs={miniTool:{saveImageToPhotosAlbum:({filePath})=>{calls++;assert(filePath.startsWith('data:image/png'));return Promise.resolve({errMsg:'saveImageToPhotosAlbum:ok'});}}};assert.equal(calls,0);assert.equal((await c.LifePlatform.saveImage('data:image/png;base64,abc')).saved,true);assert.equal(calls,1);c.xhs.miniTool.saveImageToPhotosAlbum=()=>Promise.reject(Error('no'));await assert.rejects(c.LifePlatform.saveImage('data:image/png;base64,abc'));});
test('损坏或伪造收益记录拒绝恢复',()=>{const C=env().LifeCore;let s=C.initial();s.answers=['building','better','money','subscription'];const card=C.recommend(s.answers).find(x=>x.calc);s=C.collect(s,card,C.calc('subscription',{fee:30,months:12}));assert(C.validate(s));s.deck[0].estimate.value=999;assert.equal(C.validate(s),false);});

test('未知估算类型即使未填金额也拒绝恢复且不覆盖',()=>{const e=env(),C=e.LifeCore;let s=C.initial();s.answers=['building','better','money','subscription'];s=C.collect(s,C.recommend(s.answers)[0],null);s.deck[0].calc='bogus';assert.equal(C.validate(s),false);let writes=0;const c=env({getItem:()=>JSON.stringify(s),setItem:()=>writes++});assert(c.LifePlatform.load().error);assert.throws(()=>c.LifePlatform.save(C.initial()));assert.equal(writes,0);});

test('旧版已收藏卡保留，旧回答不被猜测为人生阶段',()=>{const C=env().LifeCore;let s=C.initial();s.answers=['building','better','money','subscription'];s=C.collect(s,C.recommend(s.answers)[0],null);s.version=1;s.answers=['better','money','subscription','quick'];const migrated=C.restore(s);assert.equal(migrated.version,2);assert.equal(migrated.answers.length,0);assert.deepEqual(migrated.deck,s.deck);assert.equal(s.version,1);assert(C.validate(migrated));});
test('阶段实际改变下一问文案和处境顺序，不排除其他人生方向',()=>{const C=env().LifeCore;assert.notEqual(C.question(['starting']).options[0].title,C.question(['building']).options[0].title);assert.equal(C.question(['changing','prepare','family']).options[0].id,'elder');assert.equal(C.question(['starting','choose','career']).options[0].id,'firstpath');assert.equal(C.question(['changing','choose','career']).options[0].id,'restart');});
