const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function env(){const c={console,Date,Math,Set,Map,Number,setTimeout,clearTimeout,localStorage:{getItem:()=>null,setItem(){}}};c.window=c;vm.createContext(c);for(const f of ['content','sources','catalog','reading','core','interests','routes','applicability','exploration','platform'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/'+f+'.js'),'utf8'),c);return c;}
function assertValid(c,s){assert.equal(c.LifeCore.validate(s),true,JSON.stringify(s).slice(0,160));assert.equal(c.LifeCore.validate(JSON.parse(JSON.stringify(s))),true);}
const PREF={empty:'general',work_context:'general',breadth:'any',care_target:'general',grad_direction:'any',age_check:'no',applicability:'later',context_confirm:'no'};
function answerFor(q){const want=PREF[q.id];return q.options.some(o=>o.id===want)?want:q.options[0].id;}
function resume(c,s){let i=0;while(c.LifeExplore.question(s)&&i++<8)s=c.LifeExplore.answer(s,answerFor(c.LifeExplore.question(s)));return s;}
function setup(c,profile,need){const E=c.LifeExplore;return resume(c,E.selectNeed(E.selectProfile(c.LifeCore.initial(),profile||'working'),need||'save_money'));}
function picked(c,s,i){return resume(c,c.LifeExplore.pick(s,s.batch[i||0]));}
function aspect(c,id){return c.LifeRoutes.get(id).aspect;}
function sub(c,id){return c.LifeRoutes.get(id).subtopic;}
function followIds(c,card){if(!card)return [];const out=[];c.LifeRoutes.followups(card).forEach(f=>(f.ids||[]).forEach(id=>out.push(id)));return out;}
function fill(c,s){const E=c.LifeExplore;let guard=0;while(s.deck.length<10&&guard++<60){s=resume(c,s);assert(s.batch.length>0,'still dealing');s=resume(c,E.pick(s,s.batch[0]));}return s;}
const V6={version:6,contexts:[],pendingCard:null,trail:[],profile:'student',need:'energy',deck:[{id:'source-5-1',title:'关掉所有自动续费，改为到期手动续',question:'有些会员已经不用了，却还在每月扣钱吗？',chapterId:5,chapterTitle:'不要浪费钱',heading:'1. 关掉所有自动续费，改为到期手动续',url:'https://github.com/eternity4719/HowToLiveBetter/blob/main/book/05-不要浪费钱.md',tags:['bills','student','earlywork','working','family','retired','money'],group:'bills',steps:[],benefit:'省下的钱，等于你已经不用、却还在扣费的那些订阅加起来的钱。每个人不一样，没有统一数字。',calc:'subscription',chapters:[5],sourceLabel:'《HowToLiveBetter》第5章 · 不要浪费钱',boundary:'以下是仓库原文，保留作者的说法、来源和备注；未逐条核验。',sourceOriginal:true,action:'关掉所有自动续费，改为到期手动续',done:true,savedAt:'2026-09-27T14:22:42.548Z',estimate:{kind:'money',value:360,unit:'元',label:'未来 12 个月预计减少支出',formula:'30 元/月 × 12 个月',assumption:'仅计算已确认不用、可以取消且在所填月份不再扣费的月付订阅。不含已付费用退款。',values:{fee:30,months:12}}},{id:'source-23-14',title:'学完先合上书自己考一遍，别回头重读',question:'学完先合上书自己考一遍，别回头重读',chapterId:23,chapterTitle:'学什么技能划算',heading:'14. 学完先合上书自己考一遍，别回头重读',url:'https://github.com/eternity4719/HowToLiveBetter/blob/main/book/23-学什么技能划算.md',tags:['learning'],group:'learning',steps:[],benefit:'练习性测验被综述评为最高一档，对不同年龄和能力的学习者都有效。',calc:null,chapters:[23],sourceLabel:'《HowToLiveBetter》第23章 · 学什么技能划算',boundary:'以下是仓库原文，保留作者的说法、来源和备注；未逐条核验。',sourceOriginal:true,action:'学完先合上书自己考一遍，别回头重读',done:false,savedAt:'2026-09-27T14:22:42.554Z',estimate:null}],archive:[],seen:['source-2-20','source-3-1','source-13-3','source-5-1','source-23-14'],batch:['source-2-20','source-3-1','source-13-3'],decisions:{'source-5-1':'add','source-23-14':'add'},round:1,emptyRounds:0,checkpoints:[],pendingQuestion:null,answers:{},visited:[],estimates:{},sessionId:'mujwrdkg-xfnb83tk'};

test('七个阶段加“都可以”，每个阶段三个具体目标，选完都是合法状态',()=>{const c=env(),E=c.LifeExplore;const ids=E.profiles.map(p=>p.id);assert.equal(ids.length,7);assert(ids.includes('jobseeker'));for(const p of ids.concat(['any'])){const goals=E.goalsFor(p);assert.equal(goals.length,3,p);assert.equal(new Set(goals).size,3);const q=E.needs(E.selectProfile(c.LifeCore.initial(),p));assert.equal(q.title,'你现在最想做到什么？');assert.equal(q.options.length,3);assert(q.options.every(o=>o.title&&o.sub));for(const g of goals){const s=E.selectNeed(E.selectProfile(c.LifeCore.initial(),p),g);assert.equal(s.goal,g);assert.equal(s.need,g);assert(s.batch.length===3||E.question(s)!==null,p+'/'+g);assertValid(c,s);}}});

test('学生提高学习效率：前三组都围绕学习方法/专注/休息/习惯，也不会追问工作情况',()=>{const c=env(),E=c.LifeExplore;const allowed=new Set(['study_methods','focus','rest','habits']);let s=setup(c,'student','study_efficiency');assert.equal(E.question(s),null);assert.equal(s.contexts.length,0);for(let r=0;r<3;r++){assert(s.batch.length>0&&s.batch.length<=3);const last=E.lastPicked(s),follow=new Set(followIds(c,last));for(const id of s.batch)assert(allowed.has(sub(c,id))||follow.has(id),id+':'+sub(c,id));s=E.pick(s,s.batch[0]);assert.equal(s.contexts.length,0);const q=E.question(s);assert.notEqual(q&&q.id,'work_context');if(q)s=resume(c,s);}assert.equal(s.deck.length,3);assertValid(c,s);});

test('求职者找工作：只给求职与相关技能，不会自动带上 ICP 备案或工伤前提',()=>{const c=env(),E=c.LifeExplore,A=c.LifeApplicability;let s=setup(c,'jobseeker','find_job');assert.equal(s.contexts.join(','),'job_search');const allowed=new Set(['job_search','skills']);for(let r=0;r<3;r++){assert(s.batch.length>0&&s.batch.length<=3);const last=E.lastPicked(s),follow=new Set(followIds(c,last));for(const id of s.batch){const req=A.get(id).requires;assert.equal(A.eligible(id,s.contexts),true);assert(!req.includes('site_operator'));assert(!req.includes('work_injury'));assert(!req.includes('employed'));assert(allowed.has(sub(c,id))||follow.has(id),id);}s=resume(c,E.pick(s,s.batch[0]));}assert(!s.contexts.includes('site_operator'));assert(!s.contexts.includes('work_injury'));assertValid(c,s);});

test('看过三组才问是否换领域，且只问一次',()=>{const c=env(),E=c.LifeExplore;let s=setup(c);assert.equal(E.question(s),null);s=E.pick(s,s.batch[0]);assert.equal(E.question(s),null);s=E.pick(s,s.batch[0]);assert.equal(E.question(s),null);s=E.pick(s,s.batch[0]);const q=E.question(s);assert.equal(q.id,'breadth');assert.equal(q.title,'想看看其他领域的建议吗？');assert.equal(s.batch.length,0);assert(s.checkpoints.includes('breadth'));s=E.answer(s,'follow');assert.equal(s.batch.length,3);for(let i=0;i<2;i++){s=E.pick(s,s.batch[0]);const q2=E.question(s);assert.notEqual(q2&&q2.id,'breadth');s=resume(c,s);}assertValid(c,s);});

test('选了“看看其他领域”后这个偏好会持续到下一组，选中一张后回到跟随',()=>{const c=env(),E=c.LifeExplore;let s=setup(c);for(let i=0;i<3;i++)s=E.pick(s,s.batch[0]);assert.equal(E.question(s).id,'breadth');const collected=new Set(s.deck.map(x=>aspect(c,x.id)));const broad=E.answer(s,'broaden'),follow=E.answer(s,'follow');const count=b=>b.batch.filter(id=>collected.has(aspect(c,id))).length;assert.notEqual(broad.batch.join(','),follow.batch.join(','));assert(count(broad)<=count(follow));const kept=E.pass(broad);assert.equal(kept.answers.breadth,'broaden');assert.equal(kept.batch.length,3);assert(count(kept)<=count(follow));const after=E.pick(broad,broad.batch[0]);assert.equal(after.answers.breadth,'any');assertValid(c,after);});

test('选择“继续这个方向”后目标相关的卡用完就留空，不会泛化到无关建议',()=>{const c=env(),E=c.LifeExplore;let s=setup(c);const rel=E.pool(s).filter(x=>E.relevant(s,x)).map(x=>x.id);s=Object.assign({},s,{answers:{breadth:'follow'},checkpoints:['breadth'],round:4,batch:[],seen:Array.from(new Set(s.seen.concat(rel)))});const out=E.deal(s);assert.equal(out.batch.length,0);assert.equal(E.recommend(out).length,0);assert(E.pool(out).some(x=>!E.relevant(out,x)&&!out.seen.includes(x.id)),'仍有无关卡但没有被拿来凑数');assertValid(c,out);});

test('选牌是原子的：过期、重复、不在本组、问题未答都会被拒绝，满十张停止',()=>{const c=env(),E=c.LifeExplore;let s=setup(c);const first=s.batch[0],stale=s.batch[1];s=E.pick(s,first);assert.equal(s.deck.length,1);assert.equal(s.trail[0],first);assert.throws(()=>E.pick(s,first));assert.throws(()=>E.pick(s,stale));assert.throws(()=>E.pick(s,'source-999-1'));let t=E.selectNeed(E.selectProfile(c.LifeCore.initial(),'family'),'care_family');assert.equal(E.question(t).id,'care_target');assert.throws(()=>E.pick(t,'source-5-1'));s=fill(c,s);assert.equal(s.deck.length,10);assert.equal(E.isComplete(s),true);assert.equal(s.batch.length,0);assert.equal(s.trail.length,10);assert.equal(new Set(s.deck.map(x=>x.id)).size,10);assert.throws(()=>E.pick(s,s.deck[0].id));assert.equal(E.pass(s),s);assertValid(c,s);});

test('跳过一组不收卡，连续两组空后给出出口，选“换个目标”可重选',()=>{const c=env(),E=c.LifeExplore;let s=setup(c);s=E.pass(s);assert.equal(s.deck.length,0);assert.equal(s.trail.length,0);assert.equal(s.round,2);assert.equal(E.question(s),null);s=E.pass(s);const q=E.question(s);assert.equal(q.id,'empty');assert.equal(q.options.length,3);assert.equal(s.batch.length,0);assert.equal(E.pass(s),s);const general=E.answer(s,'general');assert.equal(general.batch.length,3);assertValid(c,general);const changed=E.answer(s,'change');assert.equal(changed.goal,null);assert.equal(changed.batch.length,0);const again=E.selectNeed(changed,'save_time');assert.equal(again.goal,'save_time');assert.equal(again.batch.length,3);assertValid(c,again);});

test('只看不动作不会改变状态，未选的卡也不会拉低其他建议的排序',()=>{const c=env(),E=c.LifeExplore;let s=setup(c);const before=JSON.stringify(s);E.recommend(s);E.coverage(s);E.question(s);E.needs(s);assert.equal(JSON.stringify(s),before);const probe=E.pool(s).find(x=>!s.batch.includes(x.id));const scoreBefore=E.score(s,probe);const passed=E.pass(s);assert.equal(E.score(passed,probe),scoreBefore);for(const id of s.batch)assert.equal(passed.decisions[id],'skip');assert.equal(passed.deck.length,0);assertValid(c,passed);});

test('手动点开有多重前提的建议会一次列出全部前提，拒绝或稍后都不写入事实',()=>{const c=env(),E=c.LifeExplore,A=c.LifeApplicability;const id='source-5-28',requires=A.get(id).requires;assert(requires.length>1);const base=setup(c,'any','save_money');for(const choice of ['no','later']){let p=E.requestCard(base,id);assert.equal(p.pendingQuestion,'applicability');assert.equal(p.pendingCard,id);const q=E.question(p);for(const f of requires)assert(q.note.includes(A.contexts.find(x=>x.id===f).title));assertValid(c,p);p=E.answer(p,choice);assert.equal(p.contexts.length,base.contexts.length);assert.equal(p.deck.length,0);assert.equal(p.pendingCard,null);assertValid(c,p);}const yes=E.answer(E.requestCard(base,id),'confirm');assert.equal(yes.deck[0].id,id);assert.equal(yes.trail[0],id);assert.equal(yes.contexts.slice().sort().join(','),requires.slice().sort().join(','));assertValid(c,yes);});

test('确认一张建议的前提不会顺带解锁其他前提不同的建议',()=>{const c=env(),E=c.LifeExplore,A=c.LifeApplicability;const s=E.answer(E.requestCard(setup(c,'any','save_money'),'source-5-28'),'confirm');const have=new Set(s.contexts);const blocked=c.LifeCatalog.all.find(card=>A.get(card).requires.some(r=>!have.has(r)));assert(blocked,'仍有需要其他前提的建议');assert.equal(A.eligible(blocked,s.contexts),false);for(const card of E.recommend(s))assert.equal(A.eligible(card,s.contexts),true);assertValid(c,s);});

test('ICP 备案类建议不会自动出现在求职者面前，只有明确确认后才收下',()=>{const c=env(),E=c.LifeExplore,A=c.LifeApplicability,C=c.LifeCore;let s=setup(c,'jobseeker','find_job');const id='source-26-1';assert.equal(A.eligible(id,s.contexts),false);assert(!E.recommend(s).some(x=>x.id===id));const forged=Object.assign({},s,{batch:[id],seen:s.seen.concat([id])});assert.throws(()=>E.pick(forged,id));assert.equal(C.validate(forged),false);s=E.requestCard(s,id);assert.equal(E.question(s).id,'applicability');s=E.answer(s,'confirm');assert(s.contexts.includes('site_operator'));assert(s.contexts.includes('job_search'));assert.equal(s.deck[0].id,id);assert.equal(A.eligible('source-26-2',s.contexts),true);assertValid(c,s);});

test('在职与求职可以并存，在职与失业互斥且自动处理',()=>{const c=env(),E=c.LifeExplore;let s=setup(c,'any','save_money');s=E.setContext(s,'job_search',true);s=E.setContext(s,'employed',true);assert(s.contexts.includes('job_search'));assert(s.contexts.includes('employed'));assertValid(c,s);s=E.setContext(s,'unemployed',true);assert(!s.contexts.includes('employed'));assert(s.contexts.includes('unemployed'));assert(s.contexts.includes('job_search'));assertValid(c,s);s=E.setContext(s,'employed',true);assert(!s.contexts.includes('unemployed'));assert(s.contexts.includes('employed'));assertValid(c,s);assert.throws(()=>E.setContext(s,'not_a_context',true));});

test('撤销一个事实后重新计算候选，但已收的牌组保留且状态仍合法',()=>{const c=env(),E=c.LifeExplore;let s=setup(c,'working','save_money');assert.equal(s.contexts.join(','),'employed');s=resume(c,E.pick(s,s.batch[0]));const deck=JSON.stringify(s.deck);s=E.setContext(s,'employed',false);assert.equal(JSON.stringify(s.deck),deck);assert.equal(s.contexts.length,0);assert(s.batch.length>0);for(const id of s.batch)assert.equal(c.LifeApplicability.eligible(id,s.contexts),true);assert(E.contextOptions(s).every(o=>!o.active));assertValid(c,s);});

test('照顾家人时先问照顾谁，选孩子或长辈分别写入对应事实',()=>{const c=env(),E=c.LifeExplore;const base=E.selectNeed(E.selectProfile(c.LifeCore.initial(),'family'),'care_family');assert.equal(E.question(base).id,'care_target');assert.equal(base.contexts.length,0);const elder=E.answer(base,'eldercare'),child=E.answer(base,'parenting'),none=E.answer(base,'general');assert.equal(elder.contexts.length,1);assert.equal(child.contexts.length,1);assert.notEqual(elder.contexts[0],child.contexts[0]);assert(c.LifeApplicability.contexts.some(x=>x.id===elder.contexts[0]));assert(c.LifeApplicability.contexts.some(x=>x.id===child.contexts[0]));assert.equal(none.contexts.length,0);for(const s of [elder,child,none]){assert.equal(s.batch.length,3);assert.equal(E.question(s),null);assertValid(c,s);}});

test('做好家庭安排第一步就有问题或建议，且不会默认成丧葬安排',()=>{const c=env(),E=c.LifeExplore;let s=E.selectNeed(E.selectProfile(c.LifeCore.initial(),'family'),'family_plan');assert(E.question(s)!==null||s.batch.length===3);assert.equal(s.contexts.length,0);s=resume(c,s);assert.equal(s.batch.length,3);const subs=['parenting','eldercare','housing','decisions'];for(const id of s.batch)assert(subs.includes(sub(c,id)),id+':'+sub(c,id));assert.equal(s.contexts.length,0);assertValid(c,s);});

test('退休阶段不预设 60 岁以上，也不预设在照顾别人',()=>{const c=env(),E=c.LifeExplore;let s=setup(c,'retired','stay_well');assert.equal(s.contexts.length,0);assert.equal(s.batch.length,3);assert(E.contextOptions(s).every(o=>!o.active));for(let i=0;i<3;i++){s=E.pass(s);const q=E.question(s);if(q){assert(['age_check','breadth','empty'].includes(q.id));s=E.answer(s,answerFor(q));}assert.equal(s.contexts.length,0);}assertValid(c,s);let t=E.selectNeed(E.selectProfile(c.LifeCore.initial(),'retired'),'stay_well');assert.equal(t.contexts.length,0);let asked=false,guard=0;while(guard++<8){const q=E.question(t);if(q&&q.id==='age_check'){asked=true;t=E.answer(t,(q.options.find(o=>o.id==='yes')||q.options[0]).id);break;}if(q){t=E.answer(t,answerFor(q));continue;}assert.equal(t.contexts.length,0,'没问过年龄就不该有事实');t=E.pass(t);}if(asked){assert(t.contexts.length<=1);assert(t.contexts.every(x=>c.LifeApplicability.contexts.some(y=>y.id===x)));}else{assert.equal(t.contexts.length,0);}assertValid(c,t);});


test('收满十张后移掉一张会重新补齐，重新开始保留已确认的事实',()=>{const c=env(),E=c.LifeExplore;let s=fill(c,setup(c));assert.equal(s.deck.length,10);assert.equal(E.isComplete(s),true);const removed=s.deck[3].id;s=E.remove(s,removed);assert.equal(s.deck.length,9);assert.equal(E.isComplete(s),false);assert(!s.deck.some(x=>x.id===removed));assertValid(c,s);s=resume(c,E.next(s));assert(s.batch.length>0,'移除后重新发牌');s=fill(c,s);assert.equal(s.deck.length,10);assert.equal(new Set(s.deck.map(x=>x.id)).size,10);assert.equal(E.remove(s,'source-999-1'),s);assertValid(c,s);const facts=s.contexts.slice().sort();const again=E.restart(s);assert.deepEqual(again.contexts.slice().sort(),facts);assert.equal(again.deck.length,0);assert.equal(again.trail.length,0);assert.equal(again.pendingCard,null);assertValid(c,again);});

test('撤销回到上一步，原来的一组和轮次都恢复',()=>{const c=env(),E=c.LifeExplore;const before=setup(c);const snapshot=JSON.stringify(before);const after=E.pick(before,before.batch[0]);assert.equal(after.deck.length,1);const back=E.undo(after);assert.deepEqual(back.batch,before.batch);assert.equal(back.round,before.round);assert.equal(back.deck.length,0);assert.equal(back.trail.length,0);assert.equal(JSON.stringify(before),snapshot);assertValid(c,back);const passed=E.pass(before);assert.equal(passed.round,before.round+1);const backFromPass=E.undo(passed);assert.equal(backFromPass,passed);assertValid(c,backFromPass);const root=E.undo(before);assert.equal(root.round,before.round);assert.equal(root.deck.length,0);assertValid(c,root);});

test('重新估算只改数字，已完成标记和保存时间都保留',()=>{const c=env(),C=c.LifeCore;const s=C.restore(JSON.parse(JSON.stringify(V6)));const before=s.deck.find(x=>x.id==='source-5-1');assert.equal(before.estimate.value,360);const next=C.collect(s,c.LifeCatalog.get('source-5-1'),C.calc('subscription',{fee:50,months:12}));const card=next.deck.find(x=>x.id==='source-5-1');assert.equal(card.estimate.value,600);assert.equal(card.estimate.kind,'money');assert.equal(card.estimate.unit,'元');assert.equal(card.done,true);assert.equal(card.savedAt,'2026-09-27T14:22:42.548Z');assert.equal(card.id,before.id);assert.equal(next.deck.length,s.deck.length);assert.equal(s.deck.find(x=>x.id==='source-5-1').estimate.value,360,'原状态不被改写');assertValid(c,next);});

test('真实 v6 存档迁移后估算与完成状态不变，旧版本也能升上来',()=>{const c=env(),C=c.LifeCore;const raw=JSON.parse(fs.readFileSync(path.join(__dirname,'v6-fixture.json'),'utf8'));const s=C.restore(raw);assert(s);assertValid(c,s);const card=s.deck.find(x=>x.id==='source-5-1');assert(card,'存档里的卡仍在');assert.equal(card.estimate.value,360);assert.equal(card.estimate.unit,'元');assert.equal(card.done,true);assert.equal(card.savedAt,raw.deck.find(x=>x.id==='source-5-1').savedAt);const other=s.deck.find(x=>x.id==='source-23-14');assert.equal(other.done,false);assert.equal(other.estimate,null);const m6=C.restore(JSON.parse(JSON.stringify(V6)));assertValid(c,m6);assert.equal(m6.deck.find(x=>x.id==='source-5-1').estimate.value,360);for(const v of [4,5]){const old=JSON.parse(JSON.stringify(V6));old.version=v;const up=C.restore(old);assert(up,'v'+v+' 应可迁移');assertValid(c,up);assert.equal(up.version,C.initial().version);assert(up.deck.length<=10);assert(up.deck.every(x=>c.LifeCatalog.all.some(y=>y.id===x.id)));}});

test('损坏或伪造的存档一律拒绝，不会得到半个状态',()=>{const c=env(),C=c.LifeCore;const bad=[null,undefined,'{}',42,[],{},{version:C.initial().version},Object.assign({},V6,{deck:'x'}),Object.assign({},V6,{version:999}),Object.assign({},V6,{seen:[1]}),Object.assign({},V6,{deck:V6.deck.concat(V6.deck)}),Object.assign({},C.restore(V6),{batch:['source-5-1','source-5-1']}),Object.assign({},V6,{profile:'nobody'}),Object.assign({},V6,{decisions:{'source-999-1':'add'}})];for(const b of bad){assert.equal(C.validate(b),false,String(JSON.stringify(b)).slice(0,80));assert.throws(()=>C.restore(b),String(JSON.stringify(b)).slice(0,80));}assertValid(c,C.restore(JSON.parse(JSON.stringify(V6))));});

test('Opus 复核回归：从失业改为在职后存档仍能读取',()=>{const c=env(),E=c.LifeExplore,C=c.LifeCore;let s=E.setContext(setup(c),'unemployed',true);s=E.answer(E.editWorkContext(s),'employed');assert(s.contexts.includes('employed'));assert(!s.contexts.includes('unemployed'));assertValid(c,s);assert.doesNotThrow(()=>C.restore(JSON.parse(JSON.stringify(s))));});
