const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function env(storage){const c={console,Date,Set,Number,setTimeout,clearTimeout,localStorage:storage||{getItem:()=>null,setItem(){}}};c.window=c;vm.createContext(c);for(const f of ['content','sources','catalog','reading','core','interests','platform'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/'+f+'.js'),'utf8'),c);return c;}
function setup(c,domain,answers=[[],[]]){let s=c.LifeCore.initial();s=c.LifeInterests.selectProfile(s,'working');s=c.LifeInterests.selectTopic(s,domain);for(const a of answers)s=c.LifeInterests.respond(s,a);return s;}
test('all 608 originals accessible across topics; money traverses every one of its 79 items once',()=>{const c=env(),I=c.LifeInterests,C=c.LifeCore;const union=new Set();for(const topic of I.topics){let s=setup(c,topic.id),seen=new Set();I.pool(s).forEach(x=>union.add(x.id));const size=I.pool(s).length;for(let turn=0;turn<610&&s.batch.length;turn++){assert(C.validate(s));for(const id of s.batch){assert(!seen.has(id),id);seen.add(id);}s=I.next(s);}assert.equal(seen.size,size,topic.id);}assert.equal(union.size,608);const s=setup(c,'money');assert.equal(I.pool(s).length,79);assert.equal(I.pool(s).filter(x=>x.id==='source-5-1').length,1);assert(new Set(I.recommend(s).map(c=>c.group)).size>=2);});
test('answers and interest change order, never remove other suggestions',()=>{const c=env(),I=c.LifeInterests;const a=setup(c,'money',[['bills'],[]]),b=setup(c,'money',[['housing'],['housing']]);assert.equal(I.pool(a).length,I.pool(b).length);assert.notEqual(a.batch[0],b.batch[0]);const id='source-5-1';let s=I.feedback(a,id,'like');assert(I.score(s,c.LifeCatalog.get('source-5-4'))>I.score(a,c.LifeCatalog.get('source-5-4')));s=I.feedback(s,id,'skip');assert.equal(I.pool(s).length,79);assert.throws(()=>I.respond(c.LifeCore.initial(),['bad']));assert.throws(()=>I.selectTopic(a,'bad'));});
test('one source card retains full original, no synthetic steps; saved record restores safely',()=>{const c=env(),C=c.LifeCore;let s=setup(c,'money');const card=c.LifeCatalog.get('source-5-1');assert.equal(card.steps.length,0);assert.equal(c.LifeReading.sections(card).length,1);assert.equal(c.LifeReading.sections(card)[0].text,card.text);s=C.collect(s,card,C.calc('subscription',{fee:30,months:12}));assert(C.validate(s));assert.equal(s.deck[0].estimate.value,360);assert.equal(s.deck[0].text,undefined);assert.equal(c.LifeReading.sections(s.deck[0])[0].text,card.text);assert.equal(C.collect(s,card,null).deck.length,1);s.batch=['source-999-1'];assert.equal(C.validate(s),false);});
test('v1 and v2 collections survive v3 migration; damaged records remain protected',()=>{const c=env(),C=c.LifeCore;for(const version of [1,2]){const old={version,answers:version===1?['better','money','subscription','quick']:['building','better','money','subscription'],deck:[{id:'subscription-stop',title:'停掉确认不用的',action:'核对',steps:['核对'],chapters:[5],benefit:'减少扣款',sourceLabel:'旧版',done:true,calc:'subscription',estimate:C.calc('subscription',{fee:20,months:12}),savedAt:'old'}],visited:[]};assert(C.validate(old));const next=C.restore(old);assert.equal(next.version,3);assert.deepEqual(next.deck,old.deck);assert.equal(next.profile,null);assert(C.validate(next));}let writes=0;const bad=env({getItem:()=>'{bad',setItem(){writes++;}});assert(bad.LifePlatform.load().error);assert.throws(()=>bad.LifePlatform.save(bad.LifeCore.initial()));assert.equal(writes,0);});

test('presentation keeps every source body paragraph; only duplicate heading, hidden comments and 说人话 label are suppressed',()=>{const c=env();for(const card of c.LifeCatalog.all){const raw=card.text,display=c.LifeReading.displayText(raw,true);assert(!display.startsWith('### '),card.id);assert(!display.includes('<!-- 成本标签'),card.id);for(const line of raw.split('\n')){if(line.startsWith('### ')||/^\s*<!--.*-->\s*$/.test(line)||!line)continue;const body=line.startsWith('- 说人话：')?line.slice('- 说人话：'.length):line;assert(display.includes(body),card.id);}assert.equal(c.LifeCatalog.get(card.id).text,raw);}});
